// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ExperiencesDocumentDataSlicesSlice = RichTextSlice | HeroSlice;

/**
 * Content for Experiences documents
 */
interface ExperiencesDocumentData {
  /**
   * Slice Zone field in *Experiences*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ExperiencesDocumentDataSlicesSlice> /**
   * Meta Description field in *Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: experiences.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Experiences*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: experiences.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Experiences document from Prismic
 *
 * - **API ID**: `experiences`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperiencesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ExperiencesDocumentData>,
    "experiences",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | TestimonialsSlice
  | SlideshowSlice
  | TitleWithSliderCardsSlice
  | HeroSlice
  | TwoCardsWithTitleSlice
  | ThreeSliderCardsWithTitleSlice
  | SliderCardsSlice
  | TitleWithTextSlice
  | WhatsAppSectionSlice
  | InstagramCardsSlice
  | FormSlice
  | OurPartnersSlice
  | IconWIthSocialIconsSlice
  | HotelsAndVillasSlice
  | FourCardsWithTitleSlice
  | TextCardsSlice
  | ImageWithTextSlice
  | HeroWithVideoSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | RichTextSlice
  | CountryCardsSlice
  | SlideshowSlice
  | TestimonialsSlice
  | OurPartnersSlice
  | TwoCardsWithTitleSlice
  | ThreeSliderCardsWithTitleSlice
  | WhatsAppSectionSlice
  | SliderCardsSlice
  | InstagramCardsSlice
  | FourCardsWithTitleSlice
  | IconWIthSocialIconsSlice
  | FormSlice
  | TitleWithSliderCardsSlice
  | TitleWithTextSlice
  | CommingSoonSlice
  | HotelsAndVillasSlice
  | TextCardsSlice
  | ImageWithTextSlice
  | HeroSlice
  | HeroWithVideoSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;
}

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * WhatsApp field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.whatsapp
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  whatsapp: prismic.LinkField;

  /**
   * Email field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email: prismic.LinkField;

  /**
   * Instagram field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

export type AllDocumentTypes =
  | ExperiencesDocument
  | HomeDocument
  | PageDocument
  | SettingsDocument;

/**
 * Primary content in *CommingSoon → Primary*
 */
export interface CommingSoonSliceDefaultPrimary {
  /**
   * Image field in *CommingSoon → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: comming_soon.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *CommingSoon → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comming_soon.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for CommingSoon Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CommingSoonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CommingSoonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CommingSoon*
 */
type CommingSoonSliceVariation = CommingSoonSliceDefault;

/**
 * CommingSoon Shared Slice
 *
 * - **API ID**: `comming_soon`
 * - **Description**: CommingSoon
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CommingSoonSlice = prismic.SharedSlice<
  "comming_soon",
  CommingSoonSliceVariation
>;

/**
 * Primary content in *CountryCards → Primary*
 */
export interface CountryCardsSliceDefaultPrimary {
  /**
   * Title field in *CountryCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_cards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *CountryCards → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_cards.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Default variation for CountryCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CountryCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CountryCardsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CountryCards → Primary*
 */
export interface CountryCardsSliceCountryCardsPrimary {
  /**
   * Country title field in *CountryCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_cards.primary.country_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  country_title: prismic.KeyTextField;
}

/**
 * Primary content in *CountryCards → Items*
 */
export interface CountryCardsSliceCountryCardsItem {
  /**
   * Title field in *CountryCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * body field in *CountryCards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_cards.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * image field in *CountryCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: country_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;
}

/**
 * CountryCards variation for CountryCards Slice
 *
 * - **API ID**: `countryCards`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CountryCardsSliceCountryCards = prismic.SharedSliceVariation<
  "countryCards",
  Simplify<CountryCardsSliceCountryCardsPrimary>,
  Simplify<CountryCardsSliceCountryCardsItem>
>;

/**
 * Slice variation for *CountryCards*
 */
type CountryCardsSliceVariation =
  | CountryCardsSliceDefault
  | CountryCardsSliceCountryCards;

/**
 * CountryCards Shared Slice
 *
 * - **API ID**: `country_cards`
 * - **Description**: CountryCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CountryCardsSlice = prismic.SharedSlice<
  "country_cards",
  CountryCardsSliceVariation
>;

/**
 * Primary content in *Form → Primary*
 */
export interface FormSliceDefaultPrimary {
  /**
   * Title field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *Form → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSlice = prismic.SharedSlice<"form", FormSliceVariation>;

/**
 * Primary content in *FourCardsWithTitle → Primary*
 */
export interface FourCardsWithTitleSliceDefaultPrimary {
  /**
   * Title field in *FourCardsWithTitle → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards_with_title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *FourCardsWithTitle → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards_with_title.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Primary content in *FourCardsWithTitle → Items*
 */
export interface FourCardsWithTitleSliceDefaultItem {
  /**
   * title field in *FourCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards_with_title.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *FourCardsWithTitle → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards_with_title.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * body field in *FourCardsWithTitle → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards_with_title.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for FourCardsWithTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FourCardsWithTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FourCardsWithTitleSliceDefaultPrimary>,
  Simplify<FourCardsWithTitleSliceDefaultItem>
>;

/**
 * Slice variation for *FourCardsWithTitle*
 */
type FourCardsWithTitleSliceVariation = FourCardsWithTitleSliceDefault;

/**
 * FourCardsWithTitle Shared Slice
 *
 * - **API ID**: `four_cards_with_title`
 * - **Description**: FourCardsWithTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FourCardsWithTitleSlice = prismic.SharedSlice<
  "four_cards_with_title",
  FourCardsWithTitleSliceVariation
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceHeroWithSliderPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceHeroWithSliderItem {
  /**
   * image field in *Hero → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;
}

/**
 * HeroWithSlider variation for Hero Slice
 *
 * - **API ID**: `heroWithSlider`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroWithSlider = prismic.SharedSliceVariation<
  "heroWithSlider",
  Simplify<HeroSliceHeroWithSliderPrimary>,
  Simplify<HeroSliceHeroWithSliderItem>
>;

/**
 * Primary content in *Hero → Primary*
 */
export interface HeroSliceHeroWithRichTextPrimary {
  /**
   * Heading field in *Hero → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Rich text field in *Hero → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text: prismic.RichTextField;

  /**
   * Image field in *Hero → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.primary.image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;
}

/**
 * HeroWithRichText variation for Hero Slice
 *
 * - **API ID**: `heroWithRichText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroWithRichText = prismic.SharedSliceVariation<
  "heroWithRichText",
  Simplify<HeroSliceHeroWithRichTextPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceHeroWithSlider
  | HeroSliceHeroWithRichText;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *HeroWithVideo → Primary*
 */
export interface HeroWithVideoSliceDefaultPrimary {
  /**
   * Pre heading field in *HeroWithVideo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_video.primary.pre_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pre_heading: prismic.KeyTextField;

  /**
   * Heading field in *HeroWithVideo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_video.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Paragraph field in *HeroWithVideo → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_video.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Video WEBM field in *HeroWithVideo → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_video.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField;

  /**
   * video mp4 field in *HeroWithVideo → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_video.primary.video_mp4
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_mp4: prismic.LinkToMediaField;
}

/**
 * Default variation for HeroWithVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroWithVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroWithVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroWithVideo*
 */
type HeroWithVideoSliceVariation = HeroWithVideoSliceDefault;

/**
 * HeroWithVideo Shared Slice
 *
 * - **API ID**: `hero_with_video`
 * - **Description**: HeroWithVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroWithVideoSlice = prismic.SharedSlice<
  "hero_with_video",
  HeroWithVideoSliceVariation
>;

/**
 * Primary content in *HotelsAndVillas → Items*
 */
export interface HotelsAndVillasSliceDefaultItem {
  /**
   * Slider image field in *HotelsAndVillas → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hotels_and_villas.items[].slider_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  slider_image: prismic.ImageField<never>;
}

/**
 * Default variation for HotelsAndVillas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HotelsAndVillasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<HotelsAndVillasSliceDefaultItem>
>;

/**
 * Primary content in *HotelsAndVillas → Primary*
 */
export interface HotelsAndVillasSliceHotelsAndVillasWithImagePrimary {
  /**
   * Image field in *HotelsAndVillas → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hotels_and_villas.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * HotelsAndVillasWithImage variation for HotelsAndVillas Slice
 *
 * - **API ID**: `hotelsAndVillasWithImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HotelsAndVillasSliceHotelsAndVillasWithImage =
  prismic.SharedSliceVariation<
    "hotelsAndVillasWithImage",
    Simplify<HotelsAndVillasSliceHotelsAndVillasWithImagePrimary>,
    never
  >;

/**
 * Slice variation for *HotelsAndVillas*
 */
type HotelsAndVillasSliceVariation =
  | HotelsAndVillasSliceDefault
  | HotelsAndVillasSliceHotelsAndVillasWithImage;

/**
 * HotelsAndVillas Shared Slice
 *
 * - **API ID**: `hotels_and_villas`
 * - **Description**: HotelsAndVillas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HotelsAndVillasSlice = prismic.SharedSlice<
  "hotels_and_villas",
  HotelsAndVillasSliceVariation
>;

/**
 * Primary content in *IconWIthSocialIcons → Primary*
 */
export interface IconWIthSocialIconsSliceDefaultPrimary {
  /**
   * Image field in *IconWIthSocialIcons → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_w_ith_social_icons.primary.image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;
}

/**
 * Default variation for IconWIthSocialIcons Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconWIthSocialIconsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IconWIthSocialIconsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IconWIthSocialIcons*
 */
type IconWIthSocialIconsSliceVariation = IconWIthSocialIconsSliceDefault;

/**
 * IconWIthSocialIcons Shared Slice
 *
 * - **API ID**: `icon_w_ith_social_icons`
 * - **Description**: IconWIthSocialIcons
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconWIthSocialIconsSlice = prismic.SharedSlice<
  "icon_w_ith_social_icons",
  IconWIthSocialIconsSliceVariation
>;

/**
 * Primary content in *ImageWithText → Primary*
 */
export interface ImageWithTextSliceDefaultPrimary {
  /**
   * Image field in *ImageWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * paragraph field in *ImageWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Default variation for ImageWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageWithText*
 */
type ImageWithTextSliceVariation = ImageWithTextSliceDefault;

/**
 * ImageWithText Shared Slice
 *
 * - **API ID**: `image_with_text`
 * - **Description**: ImageWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSlice = prismic.SharedSlice<
  "image_with_text",
  ImageWithTextSliceVariation
>;

/**
 * Primary content in *InstagramCards → Primary*
 */
export interface InstagramCardsSliceDefaultPrimary {
  /**
   * Title field in *InstagramCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: instagram_cards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * avatar field in *InstagramCards → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: instagram_cards.primary.avatar
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  avatar: prismic.LinkToMediaField;
}

/**
 * Primary content in *InstagramCards → Items*
 */
export interface InstagramCardsSliceDefaultItem {
  /**
   * Image field in *InstagramCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: instagram_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;

  /**
   * country field in *InstagramCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: instagram_cards.items[].country
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  country: prismic.KeyTextField;
}

/**
 * Default variation for InstagramCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InstagramCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InstagramCardsSliceDefaultPrimary>,
  Simplify<InstagramCardsSliceDefaultItem>
>;

/**
 * Slice variation for *InstagramCards*
 */
type InstagramCardsSliceVariation = InstagramCardsSliceDefault;

/**
 * InstagramCards Shared Slice
 *
 * - **API ID**: `instagram_cards`
 * - **Description**: InstagramCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InstagramCardsSlice = prismic.SharedSlice<
  "instagram_cards",
  InstagramCardsSliceVariation
>;

/**
 * Primary content in *OurPartners → Primary*
 */
export interface OurPartnersSliceDefaultPrimary {
  /**
   * Title field in *OurPartners → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_partners.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *OurPartners → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_partners.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Primary content in *OurPartners → Items*
 */
export interface OurPartnersSliceDefaultItem {
  /**
   * Logo field in *OurPartners → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_partners.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for OurPartners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurPartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurPartnersSliceDefaultPrimary>,
  Simplify<OurPartnersSliceDefaultItem>
>;

/**
 * Slice variation for *OurPartners*
 */
type OurPartnersSliceVariation = OurPartnersSliceDefault;

/**
 * OurPartners Shared Slice
 *
 * - **API ID**: `our_partners`
 * - **Description**: OurPartners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurPartnersSlice = prismic.SharedSlice<
  "our_partners",
  OurPartnersSliceVariation
>;

/**
 * Primary content in *RichText → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * body field in *RichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SliderCards → Primary*
 */
export interface SliderCardsSliceDefaultPrimary {
  /**
   * Title field in *SliderCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_cards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *SliderCards → Items*
 */
export interface SliderCardsSliceDefaultItem {
  /**
   * Image field in *SliderCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;

  /**
   * title field in *SliderCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for SliderCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderCardsSliceDefaultPrimary>,
  Simplify<SliderCardsSliceDefaultItem>
>;

/**
 * Slice variation for *SliderCards*
 */
type SliderCardsSliceVariation = SliderCardsSliceDefault;

/**
 * SliderCards Shared Slice
 *
 * - **API ID**: `slider_cards`
 * - **Description**: SliderCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderCardsSlice = prismic.SharedSlice<
  "slider_cards",
  SliderCardsSliceVariation
>;

/**
 * Primary content in *Slideshow → Primary*
 */
export interface SlideshowSliceDefaultPrimary {
  /**
   * Button label field in *Slideshow → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slideshow.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button link field in *Slideshow → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: slideshow.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Primary content in *Slideshow → Items*
 */
export interface SlideshowSliceDefaultItem {
  /**
   * image field in *Slideshow → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: slideshow.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;

  /**
   * country field in *Slideshow → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slideshow.items[].country
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  country: prismic.KeyTextField;
}

/**
 * Default variation for Slideshow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlideshowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SlideshowSliceDefaultPrimary>,
  Simplify<SlideshowSliceDefaultItem>
>;

/**
 * Slice variation for *Slideshow*
 */
type SlideshowSliceVariation = SlideshowSliceDefault;

/**
 * Slideshow Shared Slice
 *
 * - **API ID**: `slideshow`
 * - **Description**: Slideshow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlideshowSlice = prismic.SharedSlice<
  "slideshow",
  SlideshowSliceVariation
>;

/**
 * Primary content in *Testimonials → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Title field in *Testimonials → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Image field in *Testimonials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *TextCards → Primary*
 */
export interface TextCardsSliceDefaultPrimary {
  /**
   * Heading field in *TextCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_cards.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Link field in *TextCards → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_cards.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField;

  /**
   * Link label field in *TextCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_cards.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Primary content in *TextCards → Items*
 */
export interface TextCardsSliceDefaultItem {
  /**
   * Icon field in *TextCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: text_cards.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  icon: prismic.LinkToMediaField;

  /**
   * Title field in *TextCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *TextCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_cards.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for TextCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextCardsSliceDefaultPrimary>,
  Simplify<TextCardsSliceDefaultItem>
>;

/**
 * Slice variation for *TextCards*
 */
type TextCardsSliceVariation = TextCardsSliceDefault;

/**
 * TextCards Shared Slice
 *
 * - **API ID**: `text_cards`
 * - **Description**: TextCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextCardsSlice = prismic.SharedSlice<
  "text_cards",
  TextCardsSliceVariation
>;

/**
 * Primary content in *ThreeSliderCardsWithTitle → Primary*
 */
export interface ThreeSliderCardsWithTitleSliceDefaultPrimary {
  /**
   * Title field in *ThreeSliderCardsWithTitle → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *ThreeSliderCardsWithTitle → Items*
 */
export interface ThreeSliderCardsWithTitleSliceDefaultItem {
  /**
   * Image field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;

  /**
   * Image 2 field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].image_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_2: prismic.LinkToMediaField;

  /**
   * Image 3 field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].image_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_3: prismic.LinkToMediaField;

  /**
   * Title field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Days and nights field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].days_and_nights
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  days_and_nights: prismic.KeyTextField;

  /**
   * Button link field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for ThreeSliderCardsWithTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThreeSliderCardsWithTitleSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<ThreeSliderCardsWithTitleSliceDefaultPrimary>,
    Simplify<ThreeSliderCardsWithTitleSliceDefaultItem>
  >;

/**
 * Primary content in *ThreeSliderCardsWithTitle → Primary*
 */
export interface ThreeSliderCardsWithTitleSliceCommingSoonPrimary {
  /**
   * Title field in *ThreeSliderCardsWithTitle → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *ThreeSliderCardsWithTitle → Items*
 */
export interface ThreeSliderCardsWithTitleSliceCommingSoonItem {
  /**
   * Image field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;

  /**
   * Image 2 field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].image_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_2: prismic.LinkToMediaField;

  /**
   * Image 3 field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].image_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_3: prismic.LinkToMediaField;

  /**
   * Title field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Days and nights field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].days_and_nights
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  days_and_nights: prismic.KeyTextField;

  /**
   * Button link field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * CommingSoon variation for ThreeSliderCardsWithTitle Slice
 *
 * - **API ID**: `commingSoon`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThreeSliderCardsWithTitleSliceCommingSoon =
  prismic.SharedSliceVariation<
    "commingSoon",
    Simplify<ThreeSliderCardsWithTitleSliceCommingSoonPrimary>,
    Simplify<ThreeSliderCardsWithTitleSliceCommingSoonItem>
  >;

/**
 * Slice variation for *ThreeSliderCardsWithTitle*
 */
type ThreeSliderCardsWithTitleSliceVariation =
  | ThreeSliderCardsWithTitleSliceDefault
  | ThreeSliderCardsWithTitleSliceCommingSoon;

/**
 * ThreeSliderCardsWithTitle Shared Slice
 *
 * - **API ID**: `three_slider_cards_with_title`
 * - **Description**: ThreeSliderCardsWithTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThreeSliderCardsWithTitleSlice = prismic.SharedSlice<
  "three_slider_cards_with_title",
  ThreeSliderCardsWithTitleSliceVariation
>;

/**
 * Primary content in *TitleWithSliderCards → Primary*
 */
export interface TitleWithSliderCardsSliceDefaultPrimary {
  /**
   * Title field in *TitleWithSliderCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *TitleWithSliderCards → Items*
 */
export interface TitleWithSliderCardsSliceDefaultItem {
  /**
   * Title field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * body field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button label field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button link field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * image field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;

  /**
   * image 2 field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].image_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_2: prismic.LinkToMediaField;

  /**
   * image 3 field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].image_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_3: prismic.LinkToMediaField;
}

/**
 * Default variation for TitleWithSliderCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithSliderCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleWithSliderCardsSliceDefaultPrimary>,
  Simplify<TitleWithSliderCardsSliceDefaultItem>
>;

/**
 * Slice variation for *TitleWithSliderCards*
 */
type TitleWithSliderCardsSliceVariation = TitleWithSliderCardsSliceDefault;

/**
 * TitleWithSliderCards Shared Slice
 *
 * - **API ID**: `title_with_slider_cards`
 * - **Description**: TitleWithSliderCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithSliderCardsSlice = prismic.SharedSlice<
  "title_with_slider_cards",
  TitleWithSliderCardsSliceVariation
>;

/**
 * Primary content in *TitleWithText → Primary*
 */
export interface TitleWithTextSliceDefaultPrimary {
  /**
   * Title field in *TitleWithText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *TitleWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button label field in *TitleWithText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button link field in *TitleWithText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;
}

/**
 * Default variation for TitleWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TitleWithText → Primary*
 */
export interface TitleWithTextSliceTextWithButtonAndIconPrimary {
  /**
   * Title field in *TitleWithText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *TitleWithText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button label field in *TitleWithText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button link field in *TitleWithText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField;

  /**
   * Image field in *TitleWithText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * TextWithButtonAndIcon variation for TitleWithText Slice
 *
 * - **API ID**: `textWithButtonAndIcon`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithTextSliceTextWithButtonAndIcon =
  prismic.SharedSliceVariation<
    "textWithButtonAndIcon",
    Simplify<TitleWithTextSliceTextWithButtonAndIconPrimary>,
    never
  >;

/**
 * Slice variation for *TitleWithText*
 */
type TitleWithTextSliceVariation =
  | TitleWithTextSliceDefault
  | TitleWithTextSliceTextWithButtonAndIcon;

/**
 * TitleWithText Shared Slice
 *
 * - **API ID**: `title_with_text`
 * - **Description**: TitleWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithTextSlice = prismic.SharedSlice<
  "title_with_text",
  TitleWithTextSliceVariation
>;

/**
 * Primary content in *TwoCardsWithTitle → Primary*
 */
export interface TwoCardsWithTitleSliceDefaultPrimary {
  /**
   * Title field in *TwoCardsWithTitle → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_cards_with_title.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *TwoCardsWithTitle → Items*
 */
export interface TwoCardsWithTitleSliceDefaultItem {
  /**
   * Image field in *TwoCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: two_cards_with_title.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField;

  /**
   * Title field in *TwoCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_cards_with_title.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *TwoCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_cards_with_title.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for TwoCardsWithTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoCardsWithTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TwoCardsWithTitleSliceDefaultPrimary>,
  Simplify<TwoCardsWithTitleSliceDefaultItem>
>;

/**
 * Slice variation for *TwoCardsWithTitle*
 */
type TwoCardsWithTitleSliceVariation = TwoCardsWithTitleSliceDefault;

/**
 * TwoCardsWithTitle Shared Slice
 *
 * - **API ID**: `two_cards_with_title`
 * - **Description**: TwoCardsWithTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoCardsWithTitleSlice = prismic.SharedSlice<
  "two_cards_with_title",
  TwoCardsWithTitleSliceVariation
>;

/**
 * Primary content in *WhatsAppSection → Primary*
 */
export interface WhatsAppSectionSliceDefaultPrimary {
  /**
   * Title field in *WhatsAppSection → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whats_app_section.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for WhatsAppSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhatsAppSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhatsAppSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhatsAppSection*
 */
type WhatsAppSectionSliceVariation = WhatsAppSectionSliceDefault;

/**
 * WhatsAppSection Shared Slice
 *
 * - **API ID**: `whats_app_section`
 * - **Description**: WhatsAppSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhatsAppSectionSlice = prismic.SharedSlice<
  "whats_app_section",
  WhatsAppSectionSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ExperiencesDocument,
      ExperiencesDocumentData,
      ExperiencesDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      AllDocumentTypes,
      CommingSoonSlice,
      CommingSoonSliceDefaultPrimary,
      CommingSoonSliceVariation,
      CommingSoonSliceDefault,
      CountryCardsSlice,
      CountryCardsSliceDefaultPrimary,
      CountryCardsSliceCountryCardsPrimary,
      CountryCardsSliceCountryCardsItem,
      CountryCardsSliceVariation,
      CountryCardsSliceDefault,
      CountryCardsSliceCountryCards,
      FormSlice,
      FormSliceDefaultPrimary,
      FormSliceVariation,
      FormSliceDefault,
      FourCardsWithTitleSlice,
      FourCardsWithTitleSliceDefaultPrimary,
      FourCardsWithTitleSliceDefaultItem,
      FourCardsWithTitleSliceVariation,
      FourCardsWithTitleSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceHeroWithSliderPrimary,
      HeroSliceHeroWithSliderItem,
      HeroSliceHeroWithRichTextPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceHeroWithSlider,
      HeroSliceHeroWithRichText,
      HeroWithVideoSlice,
      HeroWithVideoSliceDefaultPrimary,
      HeroWithVideoSliceVariation,
      HeroWithVideoSliceDefault,
      HotelsAndVillasSlice,
      HotelsAndVillasSliceDefaultItem,
      HotelsAndVillasSliceHotelsAndVillasWithImagePrimary,
      HotelsAndVillasSliceVariation,
      HotelsAndVillasSliceDefault,
      HotelsAndVillasSliceHotelsAndVillasWithImage,
      IconWIthSocialIconsSlice,
      IconWIthSocialIconsSliceDefaultPrimary,
      IconWIthSocialIconsSliceVariation,
      IconWIthSocialIconsSliceDefault,
      ImageWithTextSlice,
      ImageWithTextSliceDefaultPrimary,
      ImageWithTextSliceVariation,
      ImageWithTextSliceDefault,
      InstagramCardsSlice,
      InstagramCardsSliceDefaultPrimary,
      InstagramCardsSliceDefaultItem,
      InstagramCardsSliceVariation,
      InstagramCardsSliceDefault,
      OurPartnersSlice,
      OurPartnersSliceDefaultPrimary,
      OurPartnersSliceDefaultItem,
      OurPartnersSliceVariation,
      OurPartnersSliceDefault,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SliderCardsSlice,
      SliderCardsSliceDefaultPrimary,
      SliderCardsSliceDefaultItem,
      SliderCardsSliceVariation,
      SliderCardsSliceDefault,
      SlideshowSlice,
      SlideshowSliceDefaultPrimary,
      SlideshowSliceDefaultItem,
      SlideshowSliceVariation,
      SlideshowSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TextCardsSlice,
      TextCardsSliceDefaultPrimary,
      TextCardsSliceDefaultItem,
      TextCardsSliceVariation,
      TextCardsSliceDefault,
      ThreeSliderCardsWithTitleSlice,
      ThreeSliderCardsWithTitleSliceDefaultPrimary,
      ThreeSliderCardsWithTitleSliceDefaultItem,
      ThreeSliderCardsWithTitleSliceCommingSoonPrimary,
      ThreeSliderCardsWithTitleSliceCommingSoonItem,
      ThreeSliderCardsWithTitleSliceVariation,
      ThreeSliderCardsWithTitleSliceDefault,
      ThreeSliderCardsWithTitleSliceCommingSoon,
      TitleWithSliderCardsSlice,
      TitleWithSliderCardsSliceDefaultPrimary,
      TitleWithSliderCardsSliceDefaultItem,
      TitleWithSliderCardsSliceVariation,
      TitleWithSliderCardsSliceDefault,
      TitleWithTextSlice,
      TitleWithTextSliceDefaultPrimary,
      TitleWithTextSliceTextWithButtonAndIconPrimary,
      TitleWithTextSliceVariation,
      TitleWithTextSliceDefault,
      TitleWithTextSliceTextWithButtonAndIcon,
      TwoCardsWithTitleSlice,
      TwoCardsWithTitleSliceDefaultPrimary,
      TwoCardsWithTitleSliceDefaultItem,
      TwoCardsWithTitleSliceVariation,
      TwoCardsWithTitleSliceDefault,
      WhatsAppSectionSlice,
      WhatsAppSectionSliceDefaultPrimary,
      WhatsAppSectionSliceVariation,
      WhatsAppSectionSliceDefault,
    };
  }
}
