// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type ExperiencesDocumentDataSlicesSlice =
  | TwoCardsWithTitleSlice
  | PaymentBlockSlice
  | RichTextSlice
  | HeroSlice;

/**
 * Content for Experiences documents
 */
interface ExperiencesDocumentData {
  /**
   * Days and nights field in *Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.days_and_nights
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  days_and_nights: prismic.KeyTextField;

  /**
   * Description field in *Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A little description for the card
   * - **API ID Path**: experiences.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Card image field in *Experiences*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.card_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  card_image: prismic.ImageField<never>;

  /**
   * Slice Zone field in *Experiences*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ExperiencesDocumentDataSlicesSlice> /**
   * Meta Description field in *Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: experiences.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Experiences*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: experiences.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: experiences.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField /**
   * Background color field in *Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Background color (HEX) Example - #000000
   * - **API ID Path**: experiences.background_color
   * - **Tab**: Page styles
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  background_color: prismic.KeyTextField;

  /**
   * Text color field in *Experiences*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Text color (HEX) Example - #ffffff
   * - **API ID Path**: experiences.text_color
   * - **Tab**: Page styles
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text_color: prismic.KeyTextField;
}

/**
 * Experiences document from Prismic
 *
 * - **API ID**: `experiences`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ExperiencesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ExperiencesDocumentData>,
    "experiences",
    Lang
  >;

type HomeDocumentDataSlicesSlice =
  | TestimonialsSlice
  | SlideshowSlice
  | TitleWithSliderCardsSlice
  | HeroSlice
  | TwoCardsWithTitleSlice
  | ThreeSliderCardsWithTitleSlice
  | SliderCardsSlice
  | TitleWithTextSlice
  | WhatsAppSectionSlice
  | InstagramCardsSlice
  | FormSlice
  | OurPartnersSlice
  | IconWIthSocialIconsSlice
  | HotelsAndVillasSlice
  | FourCardsWithTitleSlice
  | TextCardsSlice
  | ImageWithTextSlice
  | HeroWithVideoSlice;

/**
 * Content for Home documents
 */
interface HomeDocumentData {
  /**
   * Slice Zone field in *Home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomeDocumentDataSlicesSlice> /**
   * Meta Description field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Home document from Prismic
 *
 * - **API ID**: `home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<HomeDocumentData>, "home", Lang>;

type PageDocumentDataSlicesSlice =
  | DocRichTextSlice
  | RichTextSlice
  | CountryCardsSlice
  | SlideshowSlice
  | TestimonialsSlice
  | OurPartnersSlice
  | TwoCardsWithTitleSlice
  | ThreeSliderCardsWithTitleSlice
  | WhatsAppSectionSlice
  | SliderCardsSlice
  | InstagramCardsSlice
  | FourCardsWithTitleSlice
  | IconWIthSocialIconsSlice
  | FormSlice
  | TitleWithSliderCardsSlice
  | TitleWithTextSlice
  | CommingSoonSlice
  | HotelsAndVillasSlice
  | TextCardsSlice
  | ImageWithTextSlice
  | HeroSlice
  | HeroWithVideoSlice;

/**
 * Content for Page documents
 */
interface PageDocumentData {
  /**
   * Slice Zone field in *Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<PageDocumentDataSlicesSlice> /**
   * Meta Description field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: page.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: page.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;

  /**
   * Meta Title field in *Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: page.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_title: prismic.KeyTextField;
}

/**
 * Page document from Prismic
 *
 * - **API ID**: `page`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type PageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<PageDocumentData>, "page", Lang>;

/**
 * Item in *Settings → Navigation*
 */
export interface SettingsDocumentDataNavigationItem {
  /**
   * Label field in *Settings → Navigation*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Settings → Navigation*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Item in *Settings → Footer links*
 */
export interface SettingsDocumentDataFooterLinksItem {
  /**
   * Link field in *Settings → Footer links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

type SettingsDocumentDataSlicesSlice = never;

/**
 * Content for Settings documents
 */
interface SettingsDocumentData {
  /**
   * Logo field in *Settings*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.logo
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;

  /**
   * Navigation field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.navigation[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  navigation: prismic.GroupField<Simplify<SettingsDocumentDataNavigationItem>>;

  /**
   * Footer links field in *Settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.footer_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  footer_links: prismic.GroupField<
    Simplify<SettingsDocumentDataFooterLinksItem>
  >;

  /**
   * WhatsApp field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.whatsapp
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  whatsapp: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Email field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  email: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Instagram field in *Settings*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.instagram
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  instagram: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Slice Zone field in *Settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SettingsDocumentDataSlicesSlice>;
}

/**
 * Settings document from Prismic
 *
 * - **API ID**: `settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SettingsDocumentData>,
    "settings",
    Lang
  >;

type TravelGuideDocumentDataSlicesSlice = TravelGuideSlice;

/**
 * Content for Travel guide documents
 */
interface TravelGuideDocumentData {
  /**
   * Slice Zone field in *Travel guide*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_guide.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TravelGuideDocumentDataSlicesSlice> /**
   * Meta Title field in *Travel guide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: travel_guide.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Travel guide*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: travel_guide.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Travel guide*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_guide.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Travel guide document from Prismic
 *
 * - **API ID**: `travel_guide`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TravelGuideDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<TravelGuideDocumentData>,
    "travel_guide",
    Lang
  >;

type TravelGuidesHomeDocumentDataSlicesSlice =
  | WhatsAppSectionSlice
  | ImageWithTextSlice
  | TextCardsSlice
  | InstagramCardsSlice
  | TestimonialsSlice
  | HeroWithVideoSlice
  | TravelGuidesGridSlice
  | HeroSlice;

/**
 * Content for Travel guides home documents
 */
interface TravelGuidesHomeDocumentData {
  /**
   * Slice Zone field in *Travel guides home*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_guides_home.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<TravelGuidesHomeDocumentDataSlicesSlice> /**
   * Meta Title field in *Travel guides home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: travel_guides_home.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Travel guides home*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: travel_guides_home.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Travel guides home*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_guides_home.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Travel guides home document from Prismic
 *
 * - **API ID**: `travel_guides_home`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TravelGuidesHomeDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TravelGuidesHomeDocumentData>,
    "travel_guides_home",
    Lang
  >;

export type AllDocumentTypes =
  | ExperiencesDocument
  | HomeDocument
  | PageDocument
  | SettingsDocument
  | TravelGuideDocument
  | TravelGuidesHomeDocument;

/**
 * Primary content in *CommingSoon → Default → Primary*
 */
export interface CommingSoonSliceDefaultPrimary {
  /**
   * Image field in *CommingSoon → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: comming_soon.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *CommingSoon → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: comming_soon.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for CommingSoon Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CommingSoonSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CommingSoonSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CommingSoon*
 */
type CommingSoonSliceVariation = CommingSoonSliceDefault;

/**
 * CommingSoon Shared Slice
 *
 * - **API ID**: `comming_soon`
 * - **Description**: CommingSoon
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CommingSoonSlice = prismic.SharedSlice<
  "comming_soon",
  CommingSoonSliceVariation
>;

/**
 * Primary content in *CountryCards → Default → Primary*
 */
export interface CountryCardsSliceDefaultPrimary {
  /**
   * Title field in *CountryCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_cards.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *CountryCards → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_cards.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;
}

/**
 * Default variation for CountryCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CountryCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CountryCardsSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *CountryCards → CountryCards → Primary*
 */
export interface CountryCardsSliceCountryCardsPrimary {
  /**
   * Country title field in *CountryCards → CountryCards → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_cards.countryCards.primary.country_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  country_title: prismic.KeyTextField;
}

/**
 * Primary content in *CountryCards → Items*
 */
export interface CountryCardsSliceCountryCardsItem {
  /**
   * Title field in *CountryCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * body field in *CountryCards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: country_cards.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * image field in *CountryCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: country_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * CountryCards variation for CountryCards Slice
 *
 * - **API ID**: `countryCards`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CountryCardsSliceCountryCards = prismic.SharedSliceVariation<
  "countryCards",
  Simplify<CountryCardsSliceCountryCardsPrimary>,
  Simplify<CountryCardsSliceCountryCardsItem>
>;

/**
 * Slice variation for *CountryCards*
 */
type CountryCardsSliceVariation =
  | CountryCardsSliceDefault
  | CountryCardsSliceCountryCards;

/**
 * CountryCards Shared Slice
 *
 * - **API ID**: `country_cards`
 * - **Description**: CountryCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type CountryCardsSlice = prismic.SharedSlice<
  "country_cards",
  CountryCardsSliceVariation
>;

/**
 * Item in *DocRichText → Default → Primary → group*
 */
export interface DocRichTextSliceDefaultPrimaryGroupItem {
  /**
   * Rich text field in *DocRichText → Default → Primary → group*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: doc_rich_text.default.primary.group[].rich_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text: prismic.RichTextField;

  /**
   * Table  field in *DocRichText → Default → Primary → group*
   *
   * - **Field Type**: Table
   * - **Placeholder**: *None*
   * - **API ID Path**: doc_rich_text.default.primary.group[].table
   * - **Documentation**: https://prismic.io/docs/field#table
   */
  table: prismic.TableField;
}

/**
 * Primary content in *DocRichText → Default → Primary*
 */
export interface DocRichTextSliceDefaultPrimary {
  /**
   * group field in *DocRichText → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: doc_rich_text.default.primary.group[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  group: prismic.GroupField<Simplify<DocRichTextSliceDefaultPrimaryGroupItem>>;
}

/**
 * Default variation for DocRichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DocRichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<DocRichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *DocRichText*
 */
type DocRichTextSliceVariation = DocRichTextSliceDefault;

/**
 * DocRichText Shared Slice
 *
 * - **API ID**: `doc_rich_text`
 * - **Description**: DocRichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type DocRichTextSlice = prismic.SharedSlice<
  "doc_rich_text",
  DocRichTextSliceVariation
>;

/**
 * Primary content in *Form → Default → Primary*
 */
export interface FormSliceDefaultPrimary {
  /**
   * Title field in *Form → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *Form → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: form.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for Form Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FormSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Form*
 */
type FormSliceVariation = FormSliceDefault;

/**
 * Form Shared Slice
 *
 * - **API ID**: `form`
 * - **Description**: Form
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FormSlice = prismic.SharedSlice<"form", FormSliceVariation>;

/**
 * Primary content in *FourCardsWithTitle → Default → Primary*
 */
export interface FourCardsWithTitleSliceDefaultPrimary {
  /**
   * Title field in *FourCardsWithTitle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards_with_title.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *FourCardsWithTitle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards_with_title.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Primary content in *FourCardsWithTitle → Items*
 */
export interface FourCardsWithTitleSliceDefaultItem {
  /**
   * title field in *FourCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards_with_title.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *FourCardsWithTitle → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards_with_title.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * body field in *FourCardsWithTitle → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: four_cards_with_title.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for FourCardsWithTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FourCardsWithTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FourCardsWithTitleSliceDefaultPrimary>,
  Simplify<FourCardsWithTitleSliceDefaultItem>
>;

/**
 * Slice variation for *FourCardsWithTitle*
 */
type FourCardsWithTitleSliceVariation = FourCardsWithTitleSliceDefault;

/**
 * FourCardsWithTitle Shared Slice
 *
 * - **API ID**: `four_cards_with_title`
 * - **Description**: FourCardsWithTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FourCardsWithTitleSlice = prismic.SharedSlice<
  "four_cards_with_title",
  FourCardsWithTitleSliceVariation
>;

/**
 * Primary content in *Hero → Default → Primary*
 */
export interface HeroSliceDefaultPrimary {
  /**
   * Heading field in *Hero → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Image field in *Hero → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for Hero Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *Hero → HeroWithSlider → Primary*
 */
export interface HeroSliceHeroWithSliderPrimary {
  /**
   * Heading field in *Hero → HeroWithSlider → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithSlider.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceHeroWithSliderItem {
  /**
   * image field in *Hero → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * HeroWithSlider variation for Hero Slice
 *
 * - **API ID**: `heroWithSlider`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroWithSlider = prismic.SharedSliceVariation<
  "heroWithSlider",
  Simplify<HeroSliceHeroWithSliderPrimary>,
  Simplify<HeroSliceHeroWithSliderItem>
>;

/**
 * Primary content in *Hero → HeroWithRichText → Primary*
 */
export interface HeroSliceHeroWithRichTextPrimary {
  /**
   * Heading field in *Hero → HeroWithRichText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithRichText.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Small image field in *Hero → HeroWithRichText → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithRichText.primary.small_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  small_image: prismic.ImageField<never>;

  /**
   * Rich text field in *Hero → HeroWithRichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithRichText.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text: prismic.RichTextField;

  /**
   * Image field in *Hero → HeroWithRichText → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithRichText.primary.image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * HeroWithRichText variation for Hero Slice
 *
 * - **API ID**: `heroWithRichText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroWithRichText = prismic.SharedSliceVariation<
  "heroWithRichText",
  Simplify<HeroSliceHeroWithRichTextPrimary>,
  never
>;

/**
 * Primary content in *Hero → HeroWithSliderAndRichText → Primary*
 */
export interface HeroSliceHeroWithSliderAndRichTextPrimary {
  /**
   * Heading field in *Hero → HeroWithSliderAndRichText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithSliderAndRichText.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Rich text field in *Hero → HeroWithSliderAndRichText → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithSliderAndRichText.primary.rich_text
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  rich_text: prismic.RichTextField;

  /**
   * Button label field in *Hero → HeroWithSliderAndRichText → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithSliderAndRichText.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * button link field in *Hero → HeroWithSliderAndRichText → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithSliderAndRichText.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Hero → Items*
 */
export interface HeroSliceHeroWithSliderAndRichTextItem {
  /**
   * image field in *Hero → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * HeroWithSliderAndRichText variation for Hero Slice
 *
 * - **API ID**: `heroWithSliderAndRichText`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroWithSliderAndRichText = prismic.SharedSliceVariation<
  "heroWithSliderAndRichText",
  Simplify<HeroSliceHeroWithSliderAndRichTextPrimary>,
  Simplify<HeroSliceHeroWithSliderAndRichTextItem>
>;

/**
 * Primary content in *Hero → heroWithIcons → Primary*
 */
export interface HeroSliceHeroWithIconsPrimary {
  /**
   * Heading field in *Hero → heroWithIcons → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithIcons.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * body field in *Hero → heroWithIcons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithIcons.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Image field in *Hero → heroWithIcons → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero.heroWithIcons.primary.image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * heroWithIcons variation for Hero Slice
 *
 * - **API ID**: `heroWithIcons`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSliceHeroWithIcons = prismic.SharedSliceVariation<
  "heroWithIcons",
  Simplify<HeroSliceHeroWithIconsPrimary>,
  never
>;

/**
 * Slice variation for *Hero*
 */
type HeroSliceVariation =
  | HeroSliceDefault
  | HeroSliceHeroWithSlider
  | HeroSliceHeroWithRichText
  | HeroSliceHeroWithSliderAndRichText
  | HeroSliceHeroWithIcons;

/**
 * Hero Shared Slice
 *
 * - **API ID**: `hero`
 * - **Description**: Hero
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSlice = prismic.SharedSlice<"hero", HeroSliceVariation>;

/**
 * Primary content in *HeroWithVideo → Default → Primary*
 */
export interface HeroWithVideoSliceDefaultPrimary {
  /**
   * Pre heading field in *HeroWithVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_video.default.primary.pre_heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  pre_heading: prismic.KeyTextField;

  /**
   * Heading field in *HeroWithVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_video.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Paragraph field in *HeroWithVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_video.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Video WEBM field in *HeroWithVideo → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_video.default.primary.video
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * video mp4 field in *HeroWithVideo → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_with_video.default.primary.video_mp4
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_mp4: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for HeroWithVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroWithVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroWithVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroWithVideo*
 */
type HeroWithVideoSliceVariation = HeroWithVideoSliceDefault;

/**
 * HeroWithVideo Shared Slice
 *
 * - **API ID**: `hero_with_video`
 * - **Description**: HeroWithVideo
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroWithVideoSlice = prismic.SharedSlice<
  "hero_with_video",
  HeroWithVideoSliceVariation
>;

/**
 * Primary content in *HotelsAndVillas → Items*
 */
export interface HotelsAndVillasSliceDefaultItem {
  /**
   * Slider image field in *HotelsAndVillas → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hotels_and_villas.items[].slider_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  slider_image: prismic.ImageField<never>;
}

/**
 * Default variation for HotelsAndVillas Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HotelsAndVillasSliceDefault = prismic.SharedSliceVariation<
  "default",
  Record<string, never>,
  Simplify<HotelsAndVillasSliceDefaultItem>
>;

/**
 * Primary content in *HotelsAndVillas → HotelsAndVillasWithImage → Primary*
 */
export interface HotelsAndVillasSliceHotelsAndVillasWithImagePrimary {
  /**
   * Image field in *HotelsAndVillas → HotelsAndVillasWithImage → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hotels_and_villas.hotelsAndVillasWithImage.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * HotelsAndVillasWithImage variation for HotelsAndVillas Slice
 *
 * - **API ID**: `hotelsAndVillasWithImage`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HotelsAndVillasSliceHotelsAndVillasWithImage =
  prismic.SharedSliceVariation<
    "hotelsAndVillasWithImage",
    Simplify<HotelsAndVillasSliceHotelsAndVillasWithImagePrimary>,
    never
  >;

/**
 * Slice variation for *HotelsAndVillas*
 */
type HotelsAndVillasSliceVariation =
  | HotelsAndVillasSliceDefault
  | HotelsAndVillasSliceHotelsAndVillasWithImage;

/**
 * HotelsAndVillas Shared Slice
 *
 * - **API ID**: `hotels_and_villas`
 * - **Description**: HotelsAndVillas
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HotelsAndVillasSlice = prismic.SharedSlice<
  "hotels_and_villas",
  HotelsAndVillasSliceVariation
>;

/**
 * Primary content in *IconWIthSocialIcons → Default → Primary*
 */
export interface IconWIthSocialIconsSliceDefaultPrimary {
  /**
   * Image field in *IconWIthSocialIcons → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: icon_w_ith_social_icons.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for IconWIthSocialIcons Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconWIthSocialIconsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<IconWIthSocialIconsSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *IconWIthSocialIcons*
 */
type IconWIthSocialIconsSliceVariation = IconWIthSocialIconsSliceDefault;

/**
 * IconWIthSocialIcons Shared Slice
 *
 * - **API ID**: `icon_w_ith_social_icons`
 * - **Description**: IconWIthSocialIcons
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type IconWIthSocialIconsSlice = prismic.SharedSlice<
  "icon_w_ith_social_icons",
  IconWIthSocialIconsSliceVariation
>;

/**
 * Primary content in *ImageWithText → Default → Primary*
 */
export interface ImageWithTextSliceDefaultPrimary {
  /**
   * Image field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * paragraph field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  paragraph: prismic.RichTextField;

  /**
   * spacing field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: 16px
   * - **API ID Path**: image_with_text.default.primary.spacing
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  spacing: prismic.SelectField<"16px" | "64px" | "0px", "filled">;

  /**
   * Button label field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button link field in *ImageWithText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: image_with_text.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for ImageWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ImageWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *ImageWithText*
 */
type ImageWithTextSliceVariation = ImageWithTextSliceDefault;

/**
 * ImageWithText Shared Slice
 *
 * - **API ID**: `image_with_text`
 * - **Description**: ImageWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ImageWithTextSlice = prismic.SharedSlice<
  "image_with_text",
  ImageWithTextSliceVariation
>;

/**
 * Primary content in *InstagramCards → Default → Primary*
 */
export interface InstagramCardsSliceDefaultPrimary {
  /**
   * Title field in *InstagramCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: instagram_cards.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * avatar field in *InstagramCards → Default → Primary*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: instagram_cards.default.primary.avatar
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  avatar: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Primary content in *InstagramCards → Items*
 */
export interface InstagramCardsSliceDefaultItem {
  /**
   * Image field in *InstagramCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: instagram_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * country field in *InstagramCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: instagram_cards.items[].country
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  country: prismic.KeyTextField;
}

/**
 * Default variation for InstagramCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InstagramCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InstagramCardsSliceDefaultPrimary>,
  Simplify<InstagramCardsSliceDefaultItem>
>;

/**
 * Slice variation for *InstagramCards*
 */
type InstagramCardsSliceVariation = InstagramCardsSliceDefault;

/**
 * InstagramCards Shared Slice
 *
 * - **API ID**: `instagram_cards`
 * - **Description**: InstagramCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type InstagramCardsSlice = prismic.SharedSlice<
  "instagram_cards",
  InstagramCardsSliceVariation
>;

/**
 * Primary content in *OurPartners → Default → Primary*
 */
export interface OurPartnersSliceDefaultPrimary {
  /**
   * Title field in *OurPartners → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_partners.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *OurPartners → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: our_partners.default.primary.paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Primary content in *OurPartners → Items*
 */
export interface OurPartnersSliceDefaultItem {
  /**
   * Logo field in *OurPartners → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: our_partners.items[].logo
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  logo: prismic.ImageField<never>;
}

/**
 * Default variation for OurPartners Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurPartnersSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<OurPartnersSliceDefaultPrimary>,
  Simplify<OurPartnersSliceDefaultItem>
>;

/**
 * Slice variation for *OurPartners*
 */
type OurPartnersSliceVariation = OurPartnersSliceDefault;

/**
 * OurPartners Shared Slice
 *
 * - **API ID**: `our_partners`
 * - **Description**: OurPartners
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type OurPartnersSlice = prismic.SharedSlice<
  "our_partners",
  OurPartnersSliceVariation
>;

/**
 * Primary content in *PaymentBlock → Default → Primary*
 */
export interface PaymentBlockSliceDefaultPrimary {
  /**
   * Body field in *PaymentBlock → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Primary content in *PaymentBlock → Items*
 */
export interface PaymentBlockSliceDefaultItem {
  /**
   * image field in *PaymentBlock → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for PaymentBlock Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PaymentBlockSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<PaymentBlockSliceDefaultPrimary>,
  Simplify<PaymentBlockSliceDefaultItem>
>;

/**
 * Primary content in *PaymentBlock → PaymentBlockWithButtons → Primary*
 */
export interface PaymentBlockSlicePaymentBlockWithImagesPrimary {
  /**
   * Body field in *PaymentBlock → PaymentBlockWithButtons → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.paymentBlockWithImages.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Date field in *PaymentBlock → PaymentBlockWithButtons → Primary*
   *
   * - **Field Type**: Timestamp
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.paymentBlockWithImages.primary.date
   * - **Documentation**: https://prismic.io/docs/field#timestamp
   */
  date: prismic.TimestampField;

  /**
   * Currency field in *PaymentBlock → PaymentBlockWithButtons → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: USD
   * - **API ID Path**: payment_block.paymentBlockWithImages.primary.currency
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  currency: prismic.SelectField<"USD" | "EUR", "filled">;

  /**
   * Payment code field in *PaymentBlock → PaymentBlockWithButtons → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: DPB - $$$, RBB - Euro
   * - **Default Value**: RBB
   * - **API ID Path**: payment_block.paymentBlockWithImages.primary.payment_code
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  payment_code: prismic.SelectField<"RBB" | "DPB", "filled">;
}

/**
 * Primary content in *PaymentBlock → Items*
 */
export interface PaymentBlockSlicePaymentBlockWithImagesItem {
  /**
   * Product title (button) field in *PaymentBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.items[].product_title_button
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  product_title_button: prismic.KeyTextField;

  /**
   * Product price field in *PaymentBlock → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.items[].product_price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  product_price: prismic.NumberField;

  /**
   * Is deposit field in *PaymentBlock → Items*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: payment_block.items[].is_deposit
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  is_deposit: prismic.BooleanField;

  /**
   * Description field in *PaymentBlock → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.items[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * PaymentBlockWithButtons variation for PaymentBlock Slice
 *
 * - **API ID**: `paymentBlockWithImages`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PaymentBlockSlicePaymentBlockWithImages =
  prismic.SharedSliceVariation<
    "paymentBlockWithImages",
    Simplify<PaymentBlockSlicePaymentBlockWithImagesPrimary>,
    Simplify<PaymentBlockSlicePaymentBlockWithImagesItem>
  >;

/**
 * Primary content in *PaymentBlock → PaymenBlockWithWhatsAppAndPdf → Primary*
 */
export interface PaymentBlockSlicePaymenBlockWithWhatsAppAndPdfPrimary {
  /**
   * Body field in *PaymentBlock → PaymenBlockWithWhatsAppAndPdf → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.paymenBlockWithWhatsAppAndPdf.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button title (pdf) field in *PaymentBlock → PaymenBlockWithWhatsAppAndPdf → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.paymenBlockWithWhatsAppAndPdf.primary.button_title_pdf
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_title_pdf: prismic.KeyTextField;

  /**
   * Button link (pdf) field in *PaymentBlock → PaymenBlockWithWhatsAppAndPdf → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.paymenBlockWithWhatsAppAndPdf.primary.button_link_pdf
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link_pdf: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button description (pdf) field in *PaymentBlock → PaymenBlockWithWhatsAppAndPdf → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.paymenBlockWithWhatsAppAndPdf.primary.button_description_pdf
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_description_pdf: prismic.KeyTextField;

  /**
   * Button title (WhatsApp) field in *PaymentBlock → PaymenBlockWithWhatsAppAndPdf → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.paymenBlockWithWhatsAppAndPdf.primary.button_title_whatsapp
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_title_whatsapp: prismic.KeyTextField;

  /**
   * Button link (WhatsApp) field in *PaymentBlock → PaymenBlockWithWhatsAppAndPdf → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.paymenBlockWithWhatsAppAndPdf.primary.button_link_whatsapp
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link_whatsapp: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Button description (WhatsApp) field in *PaymentBlock → PaymenBlockWithWhatsAppAndPdf → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: payment_block.paymenBlockWithWhatsAppAndPdf.primary.button_description_whatsapp
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_description_whatsapp: prismic.KeyTextField;
}

/**
 * PaymenBlockWithWhatsAppAndPdf variation for PaymentBlock Slice
 *
 * - **API ID**: `paymenBlockWithWhatsAppAndPdf`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PaymentBlockSlicePaymenBlockWithWhatsAppAndPdf =
  prismic.SharedSliceVariation<
    "paymenBlockWithWhatsAppAndPdf",
    Simplify<PaymentBlockSlicePaymenBlockWithWhatsAppAndPdfPrimary>,
    never
  >;

/**
 * Slice variation for *PaymentBlock*
 */
type PaymentBlockSliceVariation =
  | PaymentBlockSliceDefault
  | PaymentBlockSlicePaymentBlockWithImages
  | PaymentBlockSlicePaymenBlockWithWhatsAppAndPdf;

/**
 * PaymentBlock Shared Slice
 *
 * - **API ID**: `payment_block`
 * - **Description**: PaymentBlock
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type PaymentBlockSlice = prismic.SharedSlice<
  "payment_block",
  PaymentBlockSliceVariation
>;

/**
 * Primary content in *RichText → Default → Primary*
 */
export interface RichTextSliceDefaultPrimary {
  /**
   * body field in *RichText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: rich_text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for RichText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<RichTextSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *RichText*
 */
type RichTextSliceVariation = RichTextSliceDefault;

/**
 * RichText Shared Slice
 *
 * - **API ID**: `rich_text`
 * - **Description**: RichText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type RichTextSlice = prismic.SharedSlice<
  "rich_text",
  RichTextSliceVariation
>;

/**
 * Primary content in *SliderCards → Default → Primary*
 */
export interface SliderCardsSliceDefaultPrimary {
  /**
   * Title field in *SliderCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_cards.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *SliderCards → Items*
 */
export interface SliderCardsSliceDefaultItem {
  /**
   * Image field in *SliderCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * title field in *SliderCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slider_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for SliderCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SliderCardsSliceDefaultPrimary>,
  Simplify<SliderCardsSliceDefaultItem>
>;

/**
 * Slice variation for *SliderCards*
 */
type SliderCardsSliceVariation = SliderCardsSliceDefault;

/**
 * SliderCards Shared Slice
 *
 * - **API ID**: `slider_cards`
 * - **Description**: SliderCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SliderCardsSlice = prismic.SharedSlice<
  "slider_cards",
  SliderCardsSliceVariation
>;

/**
 * Primary content in *Slideshow → Default → Primary*
 */
export interface SlideshowSliceDefaultPrimary {
  /**
   * Button label field in *Slideshow → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slideshow.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button link field in *Slideshow → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: slideshow.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *Slideshow → Items*
 */
export interface SlideshowSliceDefaultItem {
  /**
   * image field in *Slideshow → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: slideshow.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * country field in *Slideshow → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: slideshow.items[].country
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  country: prismic.KeyTextField;
}

/**
 * Default variation for Slideshow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlideshowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<SlideshowSliceDefaultPrimary>,
  Simplify<SlideshowSliceDefaultItem>
>;

/**
 * Slice variation for *Slideshow*
 */
type SlideshowSliceVariation = SlideshowSliceDefault;

/**
 * Slideshow Shared Slice
 *
 * - **API ID**: `slideshow`
 * - **Description**: Slideshow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type SlideshowSlice = prismic.SharedSlice<
  "slideshow",
  SlideshowSliceVariation
>;

/**
 * Primary content in *Testimonials → Default → Primary*
 */
export interface TestimonialsSliceDefaultPrimary {
  /**
   * Title field in *Testimonials → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *Testimonials → Items*
 */
export interface TestimonialsSliceDefaultItem {
  /**
   * Image field in *Testimonials → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Title field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *Testimonials → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: testimonials.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for Testimonials Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TestimonialsSliceDefaultPrimary>,
  Simplify<TestimonialsSliceDefaultItem>
>;

/**
 * Slice variation for *Testimonials*
 */
type TestimonialsSliceVariation = TestimonialsSliceDefault;

/**
 * Testimonials Shared Slice
 *
 * - **API ID**: `testimonials`
 * - **Description**: Testimonials
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TestimonialsSlice = prismic.SharedSlice<
  "testimonials",
  TestimonialsSliceVariation
>;

/**
 * Primary content in *TextCards → Default → Primary*
 */
export interface TextCardsSliceDefaultPrimary {
  /**
   * Heading field in *TextCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_cards.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  heading: prismic.KeyTextField;

  /**
   * Link field in *TextCards → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: text_cards.default.primary.link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;

  /**
   * Link label field in *TextCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_cards.default.primary.link_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link_label: prismic.KeyTextField;
}

/**
 * Primary content in *TextCards → Items*
 */
export interface TextCardsSliceDefaultItem {
  /**
   * Icon field in *TextCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: text_cards.items[].icon
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  icon: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Title field in *TextCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *TextCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: text_cards.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;
}

/**
 * Default variation for TextCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TextCardsSliceDefaultPrimary>,
  Simplify<TextCardsSliceDefaultItem>
>;

/**
 * Slice variation for *TextCards*
 */
type TextCardsSliceVariation = TextCardsSliceDefault;

/**
 * TextCards Shared Slice
 *
 * - **API ID**: `text_cards`
 * - **Description**: TextCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TextCardsSlice = prismic.SharedSlice<
  "text_cards",
  TextCardsSliceVariation
>;

/**
 * Primary content in *ThreeSliderCardsWithTitle → Default → Primary*
 */
export interface ThreeSliderCardsWithTitleSliceDefaultPrimary {
  /**
   * Title field in *ThreeSliderCardsWithTitle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Spacing bottom field in *ThreeSliderCardsWithTitle → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.default.primary.spacing_bottom
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  spacing_bottom: prismic.SelectField<"0" | "30" | "60">;

  /**
   * Spacing top field in *ThreeSliderCardsWithTitle → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.default.primary.spacing_top
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  spacing_top: prismic.SelectField<"0" | "30" | "60">;
}

/**
 * Primary content in *ThreeSliderCardsWithTitle → Items*
 */
export interface ThreeSliderCardsWithTitleSliceDefaultItem {
  /**
   * Image field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Image 2 field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].image_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_2: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Image 3 field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].image_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_3: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Title field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Days and nights field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].days_and_nights
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  days_and_nights: prismic.KeyTextField;

  /**
   * Button link field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for ThreeSliderCardsWithTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThreeSliderCardsWithTitleSliceDefault =
  prismic.SharedSliceVariation<
    "default",
    Simplify<ThreeSliderCardsWithTitleSliceDefaultPrimary>,
    Simplify<ThreeSliderCardsWithTitleSliceDefaultItem>
  >;

/**
 * Primary content in *ThreeSliderCardsWithTitle → CommingSoon → Primary*
 */
export interface ThreeSliderCardsWithTitleSliceCommingSoonPrimary {
  /**
   * Title field in *ThreeSliderCardsWithTitle → CommingSoon → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.commingSoon.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *ThreeSliderCardsWithTitle → Items*
 */
export interface ThreeSliderCardsWithTitleSliceCommingSoonItem {
  /**
   * Image field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Image 2 field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].image_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_2: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Image 3 field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].image_3
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_3: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Title field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * Days and nights field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].days_and_nights
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  days_and_nights: prismic.KeyTextField;

  /**
   * Button link field in *ThreeSliderCardsWithTitle → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: three_slider_cards_with_title.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * CommingSoon variation for ThreeSliderCardsWithTitle Slice
 *
 * - **API ID**: `commingSoon`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThreeSliderCardsWithTitleSliceCommingSoon =
  prismic.SharedSliceVariation<
    "commingSoon",
    Simplify<ThreeSliderCardsWithTitleSliceCommingSoonPrimary>,
    Simplify<ThreeSliderCardsWithTitleSliceCommingSoonItem>
  >;

/**
 * Slice variation for *ThreeSliderCardsWithTitle*
 */
type ThreeSliderCardsWithTitleSliceVariation =
  | ThreeSliderCardsWithTitleSliceDefault
  | ThreeSliderCardsWithTitleSliceCommingSoon;

/**
 * ThreeSliderCardsWithTitle Shared Slice
 *
 * - **API ID**: `three_slider_cards_with_title`
 * - **Description**: ThreeSliderCardsWithTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ThreeSliderCardsWithTitleSlice = prismic.SharedSlice<
  "three_slider_cards_with_title",
  ThreeSliderCardsWithTitleSliceVariation
>;

/**
 * Primary content in *TitleWithSliderCards → Default → Primary*
 */
export interface TitleWithSliderCardsSliceDefaultPrimary {
  /**
   * Title field in *TitleWithSliderCards → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *TitleWithSliderCards → Items*
 */
export interface TitleWithSliderCardsSliceDefaultItem {
  /**
   * Title field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Paragraph field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].paragraph
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  paragraph: prismic.KeyTextField;

  /**
   * body field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button label field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button link field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * image field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * image 2 field in *TitleWithSliderCards → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_slider_cards.items[].image_2
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image_2: prismic.LinkToMediaField<prismic.FieldState, never>;
}

/**
 * Default variation for TitleWithSliderCards Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithSliderCardsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleWithSliderCardsSliceDefaultPrimary>,
  Simplify<TitleWithSliderCardsSliceDefaultItem>
>;

/**
 * Slice variation for *TitleWithSliderCards*
 */
type TitleWithSliderCardsSliceVariation = TitleWithSliderCardsSliceDefault;

/**
 * TitleWithSliderCards Shared Slice
 *
 * - **API ID**: `title_with_slider_cards`
 * - **Description**: TitleWithSliderCards
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithSliderCardsSlice = prismic.SharedSlice<
  "title_with_slider_cards",
  TitleWithSliderCardsSliceVariation
>;

/**
 * Primary content in *TitleWithText → Default → Primary*
 */
export interface TitleWithTextSliceDefaultPrimary {
  /**
   * Title field in *TitleWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *TitleWithText → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.default.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button label field in *TitleWithText → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.default.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button link field in *TitleWithText → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.default.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for TitleWithText Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithTextSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TitleWithTextSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *TitleWithText → TextWithButtonAndIcon → Primary*
 */
export interface TitleWithTextSliceTextWithButtonAndIconPrimary {
  /**
   * Title field in *TitleWithText → TextWithButtonAndIcon → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.textWithButtonAndIcon.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Body field in *TitleWithText → TextWithButtonAndIcon → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.textWithButtonAndIcon.primary.body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;

  /**
   * Button label field in *TitleWithText → TextWithButtonAndIcon → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.textWithButtonAndIcon.primary.button_label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  button_label: prismic.KeyTextField;

  /**
   * Button link field in *TitleWithText → TextWithButtonAndIcon → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.textWithButtonAndIcon.primary.button_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  button_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Image field in *TitleWithText → TextWithButtonAndIcon → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: title_with_text.textWithButtonAndIcon.primary.image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * TextWithButtonAndIcon variation for TitleWithText Slice
 *
 * - **API ID**: `textWithButtonAndIcon`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithTextSliceTextWithButtonAndIcon =
  prismic.SharedSliceVariation<
    "textWithButtonAndIcon",
    Simplify<TitleWithTextSliceTextWithButtonAndIconPrimary>,
    never
  >;

/**
 * Slice variation for *TitleWithText*
 */
type TitleWithTextSliceVariation =
  | TitleWithTextSliceDefault
  | TitleWithTextSliceTextWithButtonAndIcon;

/**
 * TitleWithText Shared Slice
 *
 * - **API ID**: `title_with_text`
 * - **Description**: TitleWithText
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TitleWithTextSlice = prismic.SharedSlice<
  "title_with_text",
  TitleWithTextSliceVariation
>;

/**
 * Primary content in *TwoCardsWithTitle → Default → Primary*
 */
export interface TwoCardsWithTitleSliceDefaultPrimary {
  /**
   * Title field in *TwoCardsWithTitle → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_cards_with_title.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Primary content in *TwoCardsWithTitle → Items*
 */
export interface TwoCardsWithTitleSliceDefaultItem {
  /**
   * Image field in *TwoCardsWithTitle → Items*
   *
   * - **Field Type**: Link to Media
   * - **Placeholder**: *None*
   * - **API ID Path**: two_cards_with_title.items[].image
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  image: prismic.LinkToMediaField<prismic.FieldState, never>;

  /**
   * Title field in *TwoCardsWithTitle → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_cards_with_title.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * paragraph field in *TwoCardsWithTitle → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: two_cards_with_title.items[].body
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  body: prismic.RichTextField;
}

/**
 * Default variation for TwoCardsWithTitle Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoCardsWithTitleSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TwoCardsWithTitleSliceDefaultPrimary>,
  Simplify<TwoCardsWithTitleSliceDefaultItem>
>;

/**
 * Slice variation for *TwoCardsWithTitle*
 */
type TwoCardsWithTitleSliceVariation = TwoCardsWithTitleSliceDefault;

/**
 * TwoCardsWithTitle Shared Slice
 *
 * - **API ID**: `two_cards_with_title`
 * - **Description**: TwoCardsWithTitle
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TwoCardsWithTitleSlice = prismic.SharedSlice<
  "two_cards_with_title",
  TwoCardsWithTitleSliceVariation
>;

/**
 * Primary content in *WhatsAppSection → Default → Primary*
 */
export interface WhatsAppSectionSliceDefaultPrimary {
  /**
   * Title field in *WhatsAppSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: whats_app_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for WhatsAppSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhatsAppSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WhatsAppSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WhatsAppSection*
 */
type WhatsAppSectionSliceVariation = WhatsAppSectionSliceDefault;

/**
 * WhatsAppSection Shared Slice
 *
 * - **API ID**: `whats_app_section`
 * - **Description**: WhatsAppSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WhatsAppSectionSlice = prismic.SharedSlice<
  "whats_app_section",
  WhatsAppSectionSliceVariation
>;

/**
 * Item in *TravelGuide → Default → Primary → Images*
 */
export interface TravelGuideSliceDefaultPrimaryImagesItem {
  /**
   * image field in *TravelGuide → Default → Primary → Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_guide.default.primary.images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *TravelGuide → Default → Primary*
 */
export interface TravelGuideSliceDefaultPrimary {
  /**
   * Images field in *TravelGuide → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_guide.default.primary.images[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  images: prismic.GroupField<
    Simplify<TravelGuideSliceDefaultPrimaryImagesItem>
  >;

  /**
   * name field in *TravelGuide → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_guide.default.primary.name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Card description field in *TravelGuide → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A small description for the product card
   * - **API ID Path**: travel_guide.default.primary.card_description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  card_description: prismic.KeyTextField;

  /**
   * description field in *TravelGuide → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_guide.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * price field in *TravelGuide → Default → Primary*
   *
   * - **Field Type**: Number
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_guide.default.primary.price
   * - **Documentation**: https://prismic.io/docs/field#number
   */
  price: prismic.NumberField;

  /**
   * Currency field in *TravelGuide → Default → Primary*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **Default Value**: DPB-USD
   * - **API ID Path**: travel_guide.default.primary.currency
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  currency: prismic.SelectField<"DPB-USD" | "RBB-EUR", "filled">;
}

/**
 * Default variation for TravelGuide Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelGuideSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TravelGuideSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TravelGuide*
 */
type TravelGuideSliceVariation = TravelGuideSliceDefault;

/**
 * TravelGuide Shared Slice
 *
 * - **API ID**: `travel_guide`
 * - **Description**: TravelGuide
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelGuideSlice = prismic.SharedSlice<
  "travel_guide",
  TravelGuideSliceVariation
>;

/**
 * Primary content in *TravelGuidesGrid → Default → Primary*
 */
export interface TravelGuidesGridSliceDefaultPrimary {
  /**
   * Title field in *TravelGuidesGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: travel_guides_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;
}

/**
 * Default variation for TravelGuidesGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelGuidesGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<TravelGuidesGridSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *TravelGuidesGrid*
 */
type TravelGuidesGridSliceVariation = TravelGuidesGridSliceDefault;

/**
 * TravelGuidesGrid Shared Slice
 *
 * - **API ID**: `travel_guides_grid`
 * - **Description**: TravelGuidesGrid
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type TravelGuidesGridSlice = prismic.SharedSlice<
  "travel_guides_grid",
  TravelGuidesGridSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      ExperiencesDocument,
      ExperiencesDocumentData,
      ExperiencesDocumentDataSlicesSlice,
      HomeDocument,
      HomeDocumentData,
      HomeDocumentDataSlicesSlice,
      PageDocument,
      PageDocumentData,
      PageDocumentDataSlicesSlice,
      SettingsDocument,
      SettingsDocumentData,
      SettingsDocumentDataNavigationItem,
      SettingsDocumentDataFooterLinksItem,
      SettingsDocumentDataSlicesSlice,
      TravelGuideDocument,
      TravelGuideDocumentData,
      TravelGuideDocumentDataSlicesSlice,
      TravelGuidesHomeDocument,
      TravelGuidesHomeDocumentData,
      TravelGuidesHomeDocumentDataSlicesSlice,
      AllDocumentTypes,
      CommingSoonSlice,
      CommingSoonSliceDefaultPrimary,
      CommingSoonSliceVariation,
      CommingSoonSliceDefault,
      CountryCardsSlice,
      CountryCardsSliceDefaultPrimary,
      CountryCardsSliceCountryCardsPrimary,
      CountryCardsSliceCountryCardsItem,
      CountryCardsSliceVariation,
      CountryCardsSliceDefault,
      CountryCardsSliceCountryCards,
      DocRichTextSlice,
      DocRichTextSliceDefaultPrimaryGroupItem,
      DocRichTextSliceDefaultPrimary,
      DocRichTextSliceVariation,
      DocRichTextSliceDefault,
      FormSlice,
      FormSliceDefaultPrimary,
      FormSliceVariation,
      FormSliceDefault,
      FourCardsWithTitleSlice,
      FourCardsWithTitleSliceDefaultPrimary,
      FourCardsWithTitleSliceDefaultItem,
      FourCardsWithTitleSliceVariation,
      FourCardsWithTitleSliceDefault,
      HeroSlice,
      HeroSliceDefaultPrimary,
      HeroSliceHeroWithSliderPrimary,
      HeroSliceHeroWithSliderItem,
      HeroSliceHeroWithRichTextPrimary,
      HeroSliceHeroWithSliderAndRichTextPrimary,
      HeroSliceHeroWithSliderAndRichTextItem,
      HeroSliceHeroWithIconsPrimary,
      HeroSliceVariation,
      HeroSliceDefault,
      HeroSliceHeroWithSlider,
      HeroSliceHeroWithRichText,
      HeroSliceHeroWithSliderAndRichText,
      HeroSliceHeroWithIcons,
      HeroWithVideoSlice,
      HeroWithVideoSliceDefaultPrimary,
      HeroWithVideoSliceVariation,
      HeroWithVideoSliceDefault,
      HotelsAndVillasSlice,
      HotelsAndVillasSliceDefaultItem,
      HotelsAndVillasSliceHotelsAndVillasWithImagePrimary,
      HotelsAndVillasSliceVariation,
      HotelsAndVillasSliceDefault,
      HotelsAndVillasSliceHotelsAndVillasWithImage,
      IconWIthSocialIconsSlice,
      IconWIthSocialIconsSliceDefaultPrimary,
      IconWIthSocialIconsSliceVariation,
      IconWIthSocialIconsSliceDefault,
      ImageWithTextSlice,
      ImageWithTextSliceDefaultPrimary,
      ImageWithTextSliceVariation,
      ImageWithTextSliceDefault,
      InstagramCardsSlice,
      InstagramCardsSliceDefaultPrimary,
      InstagramCardsSliceDefaultItem,
      InstagramCardsSliceVariation,
      InstagramCardsSliceDefault,
      OurPartnersSlice,
      OurPartnersSliceDefaultPrimary,
      OurPartnersSliceDefaultItem,
      OurPartnersSliceVariation,
      OurPartnersSliceDefault,
      PaymentBlockSlice,
      PaymentBlockSliceDefaultPrimary,
      PaymentBlockSliceDefaultItem,
      PaymentBlockSlicePaymentBlockWithImagesPrimary,
      PaymentBlockSlicePaymentBlockWithImagesItem,
      PaymentBlockSlicePaymenBlockWithWhatsAppAndPdfPrimary,
      PaymentBlockSliceVariation,
      PaymentBlockSliceDefault,
      PaymentBlockSlicePaymentBlockWithImages,
      PaymentBlockSlicePaymenBlockWithWhatsAppAndPdf,
      RichTextSlice,
      RichTextSliceDefaultPrimary,
      RichTextSliceVariation,
      RichTextSliceDefault,
      SliderCardsSlice,
      SliderCardsSliceDefaultPrimary,
      SliderCardsSliceDefaultItem,
      SliderCardsSliceVariation,
      SliderCardsSliceDefault,
      SlideshowSlice,
      SlideshowSliceDefaultPrimary,
      SlideshowSliceDefaultItem,
      SlideshowSliceVariation,
      SlideshowSliceDefault,
      TestimonialsSlice,
      TestimonialsSliceDefaultPrimary,
      TestimonialsSliceDefaultItem,
      TestimonialsSliceVariation,
      TestimonialsSliceDefault,
      TextCardsSlice,
      TextCardsSliceDefaultPrimary,
      TextCardsSliceDefaultItem,
      TextCardsSliceVariation,
      TextCardsSliceDefault,
      ThreeSliderCardsWithTitleSlice,
      ThreeSliderCardsWithTitleSliceDefaultPrimary,
      ThreeSliderCardsWithTitleSliceDefaultItem,
      ThreeSliderCardsWithTitleSliceCommingSoonPrimary,
      ThreeSliderCardsWithTitleSliceCommingSoonItem,
      ThreeSliderCardsWithTitleSliceVariation,
      ThreeSliderCardsWithTitleSliceDefault,
      ThreeSliderCardsWithTitleSliceCommingSoon,
      TitleWithSliderCardsSlice,
      TitleWithSliderCardsSliceDefaultPrimary,
      TitleWithSliderCardsSliceDefaultItem,
      TitleWithSliderCardsSliceVariation,
      TitleWithSliderCardsSliceDefault,
      TitleWithTextSlice,
      TitleWithTextSliceDefaultPrimary,
      TitleWithTextSliceTextWithButtonAndIconPrimary,
      TitleWithTextSliceVariation,
      TitleWithTextSliceDefault,
      TitleWithTextSliceTextWithButtonAndIcon,
      TwoCardsWithTitleSlice,
      TwoCardsWithTitleSliceDefaultPrimary,
      TwoCardsWithTitleSliceDefaultItem,
      TwoCardsWithTitleSliceVariation,
      TwoCardsWithTitleSliceDefault,
      WhatsAppSectionSlice,
      WhatsAppSectionSliceDefaultPrimary,
      WhatsAppSectionSliceVariation,
      WhatsAppSectionSliceDefault,
      TravelGuideSlice,
      TravelGuideSliceDefaultPrimaryImagesItem,
      TravelGuideSliceDefaultPrimary,
      TravelGuideSliceVariation,
      TravelGuideSliceDefault,
      TravelGuidesGridSlice,
      TravelGuidesGridSliceDefaultPrimary,
      TravelGuidesGridSliceVariation,
      TravelGuidesGridSliceDefault,
    };
  }
}
