// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  comming_soon: defineAsyncComponent(() => import("./CommingSoon/index.vue")),
  country_cards: defineAsyncComponent(() => import("./CountryCards/index.vue")),
  form: defineAsyncComponent(() => import("./Form/index.vue")),
  four_cards_with_title: defineAsyncComponent(
    () => import("./FourCardsWithTitle/index.vue"),
  ),
  hero: defineAsyncComponent(() => import("./Hero/index.vue")),
  hero_with_video: defineAsyncComponent(
    () => import("./HeroWithVideo/index.vue"),
  ),
  hotels_and_villas: defineAsyncComponent(
    () => import("./HotelsAndVillas/index.vue"),
  ),
  icon_w_ith_social_icons: defineAsyncComponent(
    () => import("./IconWIthSocialIcons/index.vue"),
  ),
  image_with_text: defineAsyncComponent(
    () => import("./ImageWithText/index.vue"),
  ),
  instagram_cards: defineAsyncComponent(
    () => import("./InstagramCards/index.vue"),
  ),
  our_partners: defineAsyncComponent(() => import("./OurPartners/index.vue")),
  rich_text: defineAsyncComponent(() => import("./RichText/index.vue")),
  slider_cards: defineAsyncComponent(() => import("./SliderCards/index.vue")),
  slideshow: defineAsyncComponent(() => import("./Slideshow/index.vue")),
  testimonials: defineAsyncComponent(() => import("./Testimonials/index.vue")),
  text_cards: defineAsyncComponent(() => import("./TextCards/index.vue")),
  three_slider_cards_with_title: defineAsyncComponent(
    () => import("./ThreeSliderCardsWithTitle/index.vue"),
  ),
  title_with_slider_cards: defineAsyncComponent(
    () => import("./TitleWithSliderCards/index.vue"),
  ),
  title_with_text: defineAsyncComponent(
    () => import("./TitleWithText/index.vue"),
  ),
  two_cards_with_title: defineAsyncComponent(
    () => import("./TwoCardsWithTitle/index.vue"),
  ),
  whats_app_section: defineAsyncComponent(
    () => import("./WhatsAppSection/index.vue"),
  ),
});
